import fs from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';
import {strictIntersections} from '/home/davi-benucci/Área de trabalho/WFlyer/tests/e2e/helpers/assembly-stage1-audit.ts';
const root='/home/davi-benucci/Área de trabalho/WFlyer',dir=root+'/openspec/changes/implement-scroll-driven-score-assembly-and-motion/stage-1-inherited-audit-data';
const req=createRequire(root+'/package.json'),esbuild=createRequire(req.resolve('vite'))('esbuild'),constructors={};
for(const [source,path]of [['current',root],['historical','/tmp/wflyer-access-history-x6dvq4ay']]){const r=await esbuild.build({stdin:{contents:"import {buildStoryScoreProjection} from '@/lib/story/score/projection';globalThis.__auditCenters=(input)=>Object.fromEntries(Object.entries(buildStoryScoreProjection(input.mode,input.options).branches).map(([id,b])=>[id,{points:Array.from({length:2049},(_,i)=>b.path.pointAt(i/2048)),composition:b.composition}]));",resolveDir:path,loader:'ts'},bundle:true,platform:'node',format:'iife',write:false,alias:{'@':path+'/src'}});vm.runInThisContext(r.outputFiles[0].text);constructors[source]=globalThis.__auditCenters;}
const out=dir+'/full-center-replay.jsonl',seen=new Set(fs.existsSync(out)?fs.readFileSync(out,'utf8').trim().split('\n').filter(Boolean).map(s=>JSON.parse(s).inputEvidence):[]);let count=0;
for(const file of fs.readdirSync(dir).filter(f=>f.endsWith('.json')&&(f.startsWith('lifecycle-dom-geometry-')||f.startsWith('shared-dom-geometry-')||/^current-.*-0.json$/.test(f)))){if(seen.has(file))continue;const raw=JSON.parse(fs.readFileSync(dir+'/'+file)),g=raw.replayInput?raw:raw.geometry;if(!g?.replayInput)continue;const record={inputEvidence:file,replayInput:g.replayInput,sourceInputEquivalence:'Exact same saved normalized input supplied to both constructors. Historical/source replay is not by itself a historical live-DOM-center equality proof; raw measured inputs remain in source evidence.',requiredSamples:2049,sources:{}};
for(const source of ['current','historical'])try{const values=constructors[source](g.replayInput);record.sources[source]=Object.fromEntries(Object.entries(values).map(([id,b])=>[id,{points:b.points,crossings:strictIntersections(b.points),composition:b.composition}]));}catch(e){record.sources[source]={error:e.message};}fs.appendFileSync(out,JSON.stringify(record)+'\n');count++;}
console.log('Completed exact-input center replays',count);
