// Finite supplemental sequences; no product imports or source edits.
import fs from 'node:fs';
import {inspectRenderedGeometry} from '/home/davi-benucci/Área de trabalho/WFlyer/tests/e2e/helpers/assembly-stage1-audit.ts';
async function completeDOMGeometry(page){const g=await inspectRenderedGeometry(page);const file='lifecycle-dom-geometry-'+digest(g)+'.json';if(!fs.existsSync(dir+'/'+file))fs.writeFileSync(dir+'/'+file,JSON.stringify(g));return {evidence:file,staffIntersectionCount:g.staffIntersectionCount,replayInput:g.replayInput,centerPathValidation:g.centerPathValidation};}
import {dir,manifest,digest,append,launch,contextFor,configure,open,position,snapshot,frame,focusSamples,drive} from './collect.mjs';
const runtime=page=>page.evaluate(()=>({controller:window.__WFLYER_PHASE5_MOTION__?.snapshot()||null,lifecycle:window.__WFLYER_PHASE5_MOTION_LIFECYCLE__||null,visibility:document.visibilityState,visibilityEvents:window.__auditVisibility||[],active:document.activeElement?.outerHTML?.slice(0,1000),scroll:{x:scrollX,y:scrollY},url:location.href}));
async function attempt(rec,name,fn){const r={name,startedAt:new Date().toISOString()};try{r.value=await fn();r.outcome='OBSERVED';}catch(e){r.outcome='ERROR';r.error={message:e.message,stack:e.stack};}rec.steps.push(r);return r.value;}
async function sceneProbe(page,id){const nav=await position(page,id);await frame(page);const sample=await snapshot(page,id,true);const inkfile='ink-'+digest(sample.ink)+'.json';if(!fs.existsSync(dir+'/'+inkfile))fs.writeFileSync(dir+'/'+inkfile,JSON.stringify(sample.ink));sample.ink={...sample.ink,primitives:undefined,evidence:inkfile};const content=await page.evaluate(id=>{const e=document.querySelector(`[data-chapter-id="${id}"]`)||document.getElementById(id)||document.querySelector(`[data-chapter="${id}"]`);if(!e)throw Error('Missing content '+id);return {text:e.textContent,rect:e.getBoundingClientRect().toJSON(),elements:[...e.querySelectorAll('h1,h2,h3,p,a,button,input,textarea')].map(x=>({tag:x.tagName,role:x.getAttribute('role'),text:x.textContent,rect:x.getBoundingClientRect().toJSON(),display:getComputedStyle(x).display,visibility:getComputedStyle(x).visibility,disabled:x.disabled||false})),attributes:Object.fromEntries([...e.attributes].map(a=>[a.name,a.value]))};},id);return {nav,sample,content};}
async function interaction(page,profile,id,selector,index){await position(page,id);const card=page.locator(`[data-chapter-id="${id}"] ${selector}`).nth(index);const r={id,selector,index,before:await snapshot(page,id),actions:[]};const sourceUrl=page.url();
 for(const mode of profile.modalities||['keyboard']){
  try{if(mode==='pointer'){await card.hover({timeout:4000});r.actions.push({mode,intermediate:await snapshot(page,id)});}else if(mode==='touch'){const b=await card.boundingBox();if(!b)throw Error('No touch target');await page.touchscreen.tap(b.x+2,b.y+2);r.actions.push({mode,intermediate:await snapshot(page,id)});}else{const count=await card.locator('a,button,input,[tabindex]').count();if(count){await card.locator('a,button,input,[tabindex]').first().focus();r.actions.push({mode,focus:await runtime(page),intermediate:await snapshot(page,id)});}else r.actions.push({mode,applicability:'No keyboard control in existing content card; no invented tabindex or selection behavior'});}await frame(page);if(new URL(page.url()).pathname!==new URL(sourceUrl).pathname){r.actions.at(-1).navigation={url:page.url(),meaning:'Existing card navigation observed; destination content not audited'};await page.goBack({waitUntil:'domcontentloaded',timeout:15000});await frame(page);await position(page,id);r.actions.at(-1).navigation.restoredUrl=page.url();}r.actions.at(-1).settled=await snapshot(page,id);}catch(e){r.actions.push({mode,error:e.message});}
 }
 // Existing cards are CSS hover/focus surfaces, not dialogs; record Escape with no invented dismissal assertion.
 await page.keyboard.press('Escape');await page.mouse.move(1,1);await page.evaluate(()=>document.activeElement instanceof HTMLElement&&document.activeElement.blur());await frame(page);r.restored=await snapshot(page,id);return r;}
async function accessSequence(page,api){await position(page,'application-access');await frame(page);const r={before:await snapshot(page),focus:await focusSamples(page),focusOrder:[],states:[]};await page.keyboard.press('Tab');await page.locator('form[data-app-launch-interest-state] [name=email]').focus();r.focusOrder.push(await runtime(page));for(let i=0;i<4;i++){await page.keyboard.press('Tab');r.focusOrder.push(await runtime(page));}for(const state of ['INVALID_EMAIL','SUCCESS']){try{await drive(page,api,state);await frame(page);r.states.push({state,sample:await snapshot(page),focus:await focusSamples(page)});}catch(e){r.states.push({state,error:e.message});}}return r;}
export async function runLifecycle(browser,engine,source,profile,theme){const rec={slotKey:`lifecycle/${source}/${engine}/${theme}/${profile.label}`,group:'lifecycle',source,engine,engineVersion:browser.version(),comparisonKey:`lifecycle/${engine}/${theme}/${profile.label}`,exactInputs:{profile,theme},steps:[],startedAt:new Date().toISOString()};const context=await contextFor(browser,profile,theme);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const api=await configure(page);
 await attempt(rec,'mount-SSR-first-client-readiness',async()=>({navigation:await open(page,source,profile,theme),state:await runtime(page),sample:await snapshot(page),firstClient:'SSR source metadata plus hydration runtime diagnostics; first-render equality cross-referenced to primary hydration probes; settled sample is not first-client proof'}));
 await attempt(rec,'complete-visible-DOM-geometry/mounted',()=>completeDOMGeometry(page));
 for(const id of manifest.lifecycle.scenes)await attempt(rec,'scene/'+id,()=>sceneProbe(page,id));
 for(const [id,selector] of [['professional-services','[data-service-module]'],['application-how-it-works','[data-application-how-step]'],['professional-projects','[data-project-card-item]']]){const n=await page.locator(`[data-chapter-id="${id}"] ${selector}`).count();const expected=id==='professional-services'?4:id==='application-how-it-works'?5:3;rec.steps.push({name:'interaction-inventory/'+id,outcome:n===expected?'OBSERVED':'ERROR',value:{expected,actual:n}});for(let i=0;i<expected;i++)await attempt(rec,`interaction/${id}/${i}`,()=>interaction(page,profile,id,selector,i));}
 await attempt(rec,'access-focus-failure-success',()=>accessSequence(page,api));
 await attempt(rec,'header-navigation-interruption-history',async()=>{const r={before:await runtime(page),actions:[]};for(const id of ['application-access','professional-about']){const link=page.locator(`header a[href="#${id}"],header a[data-story-navigation-target="${id}"]`).first();if(await link.count()){await link.click({timeout:4000});await page.keyboard.press('ArrowDown');await frame(page);r.actions.push({id,method:'header-link+native-key-input',state:await runtime(page)});}else{r.actions.push({id,error:'No matching existing header anchor',anchors:await page.locator('header a').evaluateAll(a=>a.map(x=>({href:x.getAttribute('href'),attributes:Object.fromEntries([...x.attributes].map(y=>[y.name,y.value]))})))});}}await page.goBack({waitUntil:'domcontentloaded',timeout:10000});r.back=await runtime(page);await page.goForward({waitUntil:'domcontentloaded',timeout:10000});await frame(page);r.forward=await runtime(page);await position(page,'home');r.restored=await runtime(page);return r;});
 if(!(await page.locator('main[data-motion-lab]').count())) await attempt(rec,'restore-after-navigation-observation',()=>open(page,source,profile,theme));
 await attempt(rec,'resize-plus64-restore-owned-rebuild',async()=>{const r={before:await runtime(page)};await page.setViewportSize({...profile.viewport,width:profile.viewport.width+64});await frame(page);r.resized=await runtime(page);try{r.resizedDOM=await completeDOMGeometry(page);}catch(e){r.resizedDOM={error:e.message};}await page.setViewportSize(profile.viewport);await frame(page);r.restored=await runtime(page);r.rebuild=await page.evaluate(async()=>{const c=window.__WFLYER_PHASE5_MOTION__;if(c&&c.snapshot().projectionMode==='horizontal-enhanced'){await c.rebuild();return c.snapshot();}return {applicability:'No enhanced rebuild owned by current mode',state:c?.snapshot()};});r.geometry=await snapshot(page);try{r.completeDOM=await completeDOMGeometry(page);}catch(e){r.completeDOM={error:e.message};}r.projectsRest=await snapshot(page,'professional-projects',true);return r;});
 await attempt(rec,'actual-hide-resume',async()=>{const before=await runtime(page);const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();await page.waitForTimeout(120);const hidden=await runtime(page);await page.bringToFront();await frame(page);const resumed=await runtime(page);await other.close();return {before,hidden,resumed,actualHiddenObserved:hidden.visibility==='hidden',limitation:hidden.visibility==='hidden'?null:'This engine/headless surface did not deliver document.hidden when another tab was foregrounded; no property override or synthetic visibility event used'};});
 await attempt(rec,'leave-return-cleanup',async()=>{const before=await runtime(page);const privacy=page.locator('a[href="/politica-de-privacidade"]').first();let method;if(await privacy.count()){await privacy.evaluate(e=>e.click());method='existing Next link click (no submission)';}else throw Error('No existing privacy route link');await page.waitForURL('**/politica-de-privacidade',{timeout:15000});const left=await runtime(page);await page.goBack({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('main[data-motion-lab]')?.getAttribute('data-motion-lifecycle')==='mounted',null,{timeout:30000});await frame(page);return {method,before,left,returned:await runtime(page),geometry:await snapshot(page),completeDOM:await completeDOMGeometry(page)};});
 rec.errors=errors;rec.rawValidatorOutcome=rec.steps.some(s=>s.outcome==='ERROR')?'ERROR':rec.steps.some(s=>s.value?.actualHiddenObserved===false)?'NOT_OBSERVED':'OBSERVED';rec.completedAt=new Date().toISOString();append('lifecycle',rec);await context.close();console.log(rec.slotKey);
}
export async function runStatic(browser,engine,source,profile){const rec={slotKey:`static/${source}/${engine}/${profile.label}`,group:'static',source,engine,engineVersion:browser.version(),comparisonKey:`static/${engine}/${profile.label}`,exactInputs:{profile},steps:[],startedAt:new Date().toISOString()};const context=await contextFor(browser,profile,profile.theme);const page=await context.newPage();const api=await configure(page);
 await attempt(rec,'load-declared-JS-media',async()=>({navigation:await open(page,source,profile,profile.theme),media:await page.evaluate(()=>({forcedColors:matchMedia('(forced-colors:active)').matches,reducedMotion:matchMedia('(prefers-reduced-motion:reduce)').matches,theme:document.documentElement.dataset.theme})),sample:await snapshot(page)}));
 for(const id of manifest.lifecycle.scenes)await attempt(rec,'native-content/'+id,()=>sceneProbe(page,id));
 await attempt(rec,'form-contact-CTA-contract',async()=>({access:await snapshot(page),forms:await page.locator('form').evaluateAll(forms=>forms.map(f=>({method:f.method,action:f.getAttribute('action'),state:f.getAttribute('data-app-launch-interest-state'),buttons:[...f.querySelectorAll('button')].map(e=>({text:e.textContent,disabled:e.disabled})),noscript:[...document.querySelectorAll('noscript')].map(e=>e.textContent)}))),links:await page.locator('a').evaluateAll(a=>a.map(e=>({href:e.getAttribute('href'),text:e.textContent,rect:e.getBoundingClientRect().toJSON()}))),noJSContract:profile.javaScriptEnabled?'Not applicable':'Native rendered form inspected; no Turnstile token or submission capability manufactured'}));
 if(profile.javaScriptEnabled)await attempt(rec,'forced-colors-focus-status-outcomes',()=>accessSequence(page,api));
 rec.rawValidatorOutcome=rec.steps.some(s=>s.outcome==='ERROR')?'ERROR':'OBSERVED';rec.completedAt=new Date().toISOString();append('static',rec);await context.close();console.log(rec.slotKey);
}
async function collectSequence(browser,engine,source,profile,theme,group){
 const slotKey=group==='lifecycle'?`lifecycle/${source}/${engine}/${theme}/${profile.label}`:`static/${source}/${engine}/${profile.label}`;
 const file=dir+'/'+group+'.jsonl';
 const recorded=()=>fs.existsSync(file)&&fs.readFileSync(file,'utf8').trim().split('\n').filter(Boolean).some(s=>JSON.parse(s).slotKey===slotKey);
 if(recorded())return;
 const startedAt=new Date().toISOString();
 try{if(group==='lifecycle')await runLifecycle(browser,engine,source,profile,theme);else await runStatic(browser,engine,source,profile);}
 catch(error){if(!recorded())append(group,{slotKey,group,source,engine,engineVersion:browser.version(),exactInputs:{profile,theme},comparisonKey:slotKey.replace('/'+source+'/','/'),steps:[],errors:[{message:error.message,stack:error.stack}],rawValidatorOutcome:'ERROR',collectorBoundary:'Sequence context/setup failed before its per-step recorder completed; independent remaining sequences continue. No unsupported-state PASS is inferred.',startedAt,completedAt:new Date().toISOString()});else append('sequence-cleanup-errors',{slotKey,message:error.message});}
 finally{for(const context of browser.contexts())try{await context.close();}catch(error){append('sequence-cleanup-errors',{slotKey,message:error.message});}}
}
if(process.argv[1]?.endsWith('/lifecycle.mjs')){
 for(const engine of manifest.controls.engines){const browser=await launch(engine);for(const profile of manifest.lifecycle.profiles)for(const theme of manifest.controls.themes)for(const source of ['historical','current'])await collectSequence(browser,engine,source,profile,theme,'lifecycle');for(const profile of manifest.staticAccessibility.profiles)for(const source of ['historical','current'])await collectSequence(browser,engine,source,profile,profile.theme,'static');await browser.close();}
}
