import fs from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import {dir,manifest,digest,append,launch,contextFor,configure,open,position,snapshot,frame} from './collect.mjs';
import {inspectRenderedGeometry,strictIntersections} from '/home/davi-benucci/Área de trabalho/WFlyer/tests/e2e/helpers/assembly-stage1-audit.ts';
const root='/home/davi-benucci/Área de trabalho/WFlyer';const req=createRequire(root+'/package.json');const esbuild=createRequire(req.resolve('vite'))('esbuild');
const bundles={};const contents=`import {buildStoryScoreProjection,STORY_SCORE_PROJECTION_MODES} from '@/lib/story/score/projection';import {storyScoreCompositionDiagnostics} from '@/lib/story/score/composition';import {ScoreSvg} from '@/components/score/ScoreSvg';import {createElement} from 'react';import {renderToStaticMarkup} from 'react-dom/server';globalThis.__auditShared=(mode,options)=>{const p=buildStoryScoreProjection(mode,options);return {mode:p.mode,fingerprints:storyScoreCompositionDiagnostics().fingerprints,branches:Object.fromEntries(Object.entries(p.branches).map(([key,b])=>[key,{composition:b.composition,model:b.model,viewBox:b.viewBox,zones:b.zones,staffSpace:b.staffSpace,eventSafety:b.eventSafety||null,homeEntry:b.homeEntry||null,center:Array.from({length:2049},(_,i)=>b.path.pointAt(i/2048)),svg:renderToStaticMarkup(createElement(ScoreSvg,{model:b.model,viewBox:b.viewBox,numericPrecision:6}))}]))};};globalThis.__auditModes=STORY_SCORE_PROJECTION_MODES;`;
for(const [source,path]of [['current',root],['historical','/tmp/wflyer-access-history-x6dvq4ay']]){const result=await esbuild.build({stdin:{contents,resolveDir:path,loader:'ts'},bundle:true,platform:'browser',format:'iife',write:false,loader:{'.svg':'dataurl'},alias:{'@':path+'/src'},define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'pure-geometry-css-only',setup(build){build.onLoad({filter:/\.module\.css$/},()=>({contents:'export default {}',loader:'js'}));}}]});bundles[source]=result.outputFiles[0].text;fs.writeFileSync(dir+'/shared-'+source+'-bundle.sha256',digest(bundles[source])+'\n');}
const save=(prefix,data)=>{const name=prefix+'-'+digest(data)+'.json';if(!fs.existsSync(dir+'/'+name))fs.writeFileSync(dir+'/'+name,JSON.stringify(data));return name;};
const project=(source,input)=>{vm.runInThisContext(bundles[source]);return globalThis.__auditShared(input.mode,input.options);};
const summary=p=>({fingerprints:p.fingerprints,branches:Object.fromEntries(Object.entries(p.branches).map(([id,b])=>[id,{centerIntersections:strictIntersections(b.center),primitiveCount:b.model.primitives.length,eventCount:b.model.motifs.flatMap(m=>m.notes).length,staffSpace:b.staffSpace,eventSafety:b.eventSafety,homeEntry:b.homeEntry}]))});
for(const engine of manifest.controls.engines){const browser=await launch(engine);
 // Same pure source bundle in Node and engine, exact existing projection modes only.
 for(const source of ['historical','current']){const page=await browser.newPage();await page.goto('about:blank');await page.addScriptTag({content:bundles[source]});vm.runInThisContext(bundles[source]);const modes=globalThis.__auditModes;for(const mode of modes){const input={mode};const node=project(source,input);const client=await page.evaluate(input=>globalThis.__auditShared(input.mode,input.options),input);append('shared-pure',{source,engine,mode,input,nodeEvidence:save('pure-node',node),clientEvidence:save('pure-client',client),sameCompleteSerializedModel:JSON.stringify(node)===JSON.stringify(client),sameSvg:Object.keys(node.branches).every(k=>node.branches[k].svg===client.branches[k].svg),node:summary(node),client:summary(client),comparisonLimitation:'Historical bundle rendered under current toolchain; no invented successor event-safety telemetry'});}await page.close();}
 for(const profile of manifest.accessEnvelope.profiles.filter(p=>p.route.endsWith('/motion')&&p.label!=='integrated-static-390x844'))for(const source of ['historical','current']){
 const rec={source,engine,profile,theme:'dark',steps:[],errors:[]};const context=await contextFor(browser,profile,'dark');const page=await context.newPage();page.on('pageerror',e=>rec.errors.push(e.message));await configure(page);try{rec.navigation=await open(page,source,profile,'dark');const g=await inspectRenderedGeometry(page);rec.geometryEvidence=save('shared-dom-geometry',g);rec.renderedStaffIntersections=g.staffIntersectionCount;rec.input=g.replayInput;rec.currentExplicit=summary(project('current',g.replayInput));rec.historicalExplicit=summary(project('historical',g.replayInput));rec.currentReplayEvidence=save('shared-projection',project('current',g.replayInput));rec.historicalReplayEvidence=save('shared-projection',project('historical',g.replayInput));rec.equivalentInputProof={sameSavedInputForBothConstructors:true,actualDOMSource:source,actualMode:g.replayInput.mode,otherSourceActualModeNotAssumed:true};
 await position(page,'professional-projects');rec.projects=await snapshot(page,'professional-projects',true);const pn=save('projects-ink',rec.projects.ink);rec.projects.ink={...rec.projects.ink,primitives:undefined,evidence:pn};
 rec.restGeneration=await page.evaluate(()=>window.__WFLYER_PHASE5_MOTION__?.snapshot());const links=page.locator('[data-project-card-link]');for(let i=0;i<await links.count();i++){await links.nth(i).focus();await frame(page);rec.steps.push({name:'focus/'+i,snapshot:await snapshot(page,'professional-projects'),generation:await page.evaluate(()=>window.__WFLYER_PHASE5_MOTION__?.snapshot())});await page.evaluate(()=>document.activeElement instanceof HTMLElement&&document.activeElement.blur());await frame(page);}
 if(g.replayInput.mode==='horizontal-enhanced'){await page.evaluate(()=>window.__WFLYER_PHASE5_MOTION__?.rebuild());await frame(page);rec.afterRebuild=await inspectRenderedGeometry(page);rec.afterRebuildEvidence=save('shared-dom-geometry',rec.afterRebuild);delete rec.afterRebuild;}
 rec.successorTelemetryApplicability=source==='historical'?'Historical source lacks successor event-safe/PC generation acceptance; shared geometry and existing lifecycle compared, absent metadata not product FAIL':'Current original tests own successor telemetry';rec.outcome='OBSERVED';
 }catch(e){rec.outcome='ERROR';rec.errors.push({message:e.message,stack:e.stack});}append('shared-runtime',rec);await context.close();console.log('shared',engine,source,profile.label);}
 await browser.close();}

// All finite observations above are awaited and persisted before explicit audit process completion.
await esbuild.stop();
process.exit(0);
